# Generated by Django 4.1.2 on 2022-10-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("album_id", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=256)),
                ("url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True, default=True)),
            ],
        ),
    ]
